version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    command: bash -c "/usr/local/bin/python -m pip install --upgrade pip &&
             python /code/config/manage.py makemigrations --noinput &&
             python /code/config/manage.py migrate --noinput &&
             python /code/config/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code/config
    ports:
      - "8000:8000"
    depends_on:
      - db
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080