# Generated by Django 3.2.9 on 2021-11-17 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_auto_20211113_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='last_used_currency',
            field=models.CharField(choices=[('CHF', 'CHF'), ('USD', 'USD'), ('EUR', 'EUR')], default='UAH', max_length=3),
        ),
    ]
