# Generated by Django 3.2.9 on 2021-11-17 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_remove_wallet_last_used_currency'),
        ('information', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informationfortransaction',
            name='last_used_currency',
            field=models.CharField(choices=[('CHF', 'CHF'), ('USD', 'USD'), ('EUR', 'EUR')], default='USD', max_length=3),
        ),
        migrations.AlterField(
            model_name='informationfortransaction',
            name='wallet',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='information', to='transactions.wallet', verbose_name='Information'),
        ),
    ]
