# Generated by Django 3.2.9 on 2021-11-17 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0002_auto_20211117_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informationfortransaction',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='informationfortransaction',
            name='start_date',
        ),
    ]
