# Generated by Django 3.2.9 on 2021-11-17 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0003_auto_20211117_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informationfortransaction',
            name='last_used_currency',
            field=models.CharField(choices=[('EUR', 'EUR'), ('CHF', 'CHF'), ('USD', 'USD')], default='EUR', max_length=3),
        ),
    ]
