# Generated by Django 3.2.9 on 2021-11-02 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualwalletuser',
            name='birth_date',
            field=models.DateField(null=True, verbose_name='Birth date'),
        ),
    ]
