# Generated by Django 3.2.9 on 2021-11-03 19:20

from django.db import migrations
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20211103_1859'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='virtualwalletuser',
            managers=[
                ('objects', user.models.CustomUserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='virtualwalletuser',
            name='username',
        ),
    ]
